
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: self-hosted  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: DemoProjectForGitHubCICDPipeline                                               # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: DemoDICDPipleineForVS\DemoProjectForGitHubCICDPipeline                     # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: DemoProjectForGitHubCICDPipeline.Package.                              # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: DemoProjectForGitHubCICDPipeline/DemoProjectForGitHubCICDPipeline.btproj                      # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      application: DemoProjectForGitHubCICDPipeline.btproj
      MSI_Path: C:\ShashankWork\CICDDemo\BTDF\MSI
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
    - uses: actions/checkout@master

    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1

    - name: VSWhere MSBuild
      run: vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Powershell   
      run: ./Deployment/CreateMSI_UAT.ps1
    
    #- name: Copy MSI   
    #  run:  Copy-Item ("C:\actions-runner\DemoDICDPipleineForVS\DemoDICDPipleineForVS\Deployment\DemoProjectForGitHubCICDPipeline-1.0.0.msi") "C:\Users\sbhosekar\Documents\Visual Studio 2012\Projects\DemoProjectForGitHubCICDPipeline\DemoDICDPipleineForVS\MSI1" -Force
      
    
