
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: DemoProjectForGitHubCICDPipeline                                               # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: DemoDICDPipleineForVS\DemoProjectForGitHubCICDPipeline                     # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: DemoProjectForGitHubCICDPipeline.Package.                              # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: DemoProjectForGitHubCICDPipeline/DemoProjectForGitHubCICDPipeline.btproj                      # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install MAUI workload
      run: dotnet workload install maui
      
     # Create the app package by building and packaging the Windows Application Packaging project
    - name: build
      run: dotnet publish $env:Wap_Project_Path -c Release -f:net6.0-windows10.0.0.0 /p:Configuration=Release 
      
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    
