name: PowerShellTest
on: [push]
jobs:
    build:
      name: Run Script
      runs-on: self-hosted 
      steps: 
        - uses: actions/checkout@v1
        - name: Scirpt
          run: ./DemoProjectForGitHubCICDPipeline/Tests/Build.Tests.ps1
          shell: pwsh
 
